version: '4'
services:
  redis:
    image: redis
    command: redis-server
    expose:
      - '6379'

    volumes:
      - redis-data:/data
      - redis-conf:/usr/local/etc/redis/redis.conf
  web:
    build: ./userapi
    ports:
      - '5000:3000'
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
volumes:
  redis-data:
  redis-conf: #
