apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-node-v1
  labels:
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
      version: v1
  template:
    metadata:
      labels:
        app: server
        version: v1
    spec:
      containers:
        - name: server
          image: dogeceptionpp123/devops_project
          ports:
            - containerPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-node-v2
  labels:
    version: v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
      version: v2
  template:
    metadata:
      labels:
        app: server
        version: v2
    spec:
      containers:
        - name: meetup-server
          image: dogeceptionpp123/dev_opv2
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    app: server
spec:
  ports:
    - port: 3000
      name: http
  selector:
    app: server
