apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    app: server
    service: server

spec:
  type: NodePort
  selector:
    app: server
  ports:
    - port: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
    service: redis

spec:
  type: NodePort
  selector:
    app: redis
  ports:
    - port: 6379
