version: '4'
services:
  redis:
    image: redis
    command: redis-server
    expose:
      - "6379"

    volumes:
      - redis-data:/data
      - redis-conf:/usr/local/etc/redis/redis.conf
  web:
    # COMPLETE HERE
    build: .
    ports:
      - "5000:8080"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
volumes:
  redis-data:
  redis-conf:      # ...
