name: lab04_ci
on: 
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]
defaults:
  run:
    working-directory: lab04

jobs:
  
  # Label of the container job
  test:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container: node:10.18-jessie

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
        
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set Up Node
        uses: actions/setup-node@v3
        with:
          node-version: '15'
      # Performs a clean installation of all dependencies in the `package.json` file
      # For more information, see https://docs.npmjs.com/cli/ci.html
      - name: Install dependencies
        run: npm install
      - name: Build 
        # Runs a script that creates a Redis client, populates
        run: npm run build --if-present
      - name : Test
        run: npm run test
    env: 
      REDIS_HOST: redis
      REDIS_PORT: 6379
  deploy:
    
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: " userapi-deploy" #Must be unique in Heroku
          heroku_email: "peaphee123456789@gmail.com"
          appdir: lab04
      